const { buildService, lambdaConfig, protectedRoute, publicRoute } = require('./serverless/services/lib/common');

module.exports = buildService({
  service: 'xoc-api-ops',
  attachToSharedHttpApi: true,
  iam: { database: true, snapshots: true, vpc: true },
  functions: (stage) => ({
    scansApi: lambdaConfig(stage, {
      handler: 'src/handlers/domains/scans.handler',
      description: 'Scans domain API',
      needsVpc: true,
      events: [
        publicRoute('POST', '/scans/ingest'),
        protectedRoute(stage, 'GET', '/scans'),
        protectedRoute(stage, 'GET', '/scans/latest'),
        protectedRoute(stage, 'GET', '/scans/summary'),
        protectedRoute(stage, 'GET', '/scans/{scanSummaryId}'),
        protectedRoute(stage, 'GET', '/scans/{scanSummaryId}/findings'),
        protectedRoute(stage, 'GET', '/scans/{scannerType}/analytics'),
        protectedRoute(stage, 'GET', '/scans/snapshots'),
        protectedRoute(stage, 'GET', '/scans/snapshots/{artifactId}'),
        protectedRoute(stage, 'GET', '/scans/snapshots/{artifactId}/payload'),
        protectedRoute(stage, 'GET', '/scans/agent/snapshots'),
        protectedRoute(stage, 'GET', '/scans/agent/snapshots/{artifactId}'),
        protectedRoute(stage, 'GET', '/scans/agent/snapshots/{artifactId}/payload'),
        protectedRoute(stage, 'GET', '/scans/agent/summaries'),
        protectedRoute(stage, 'GET', '/scans/agent/summaries/{scanSummaryId}'),
        protectedRoute(stage, 'GET', '/scans/agent/summaries/{scanSummaryId}/findings'),
        protectedRoute(stage, 'GET', '/scans/agent/findings'),
      ],
    }),
    integrationsApi: lambdaConfig(stage, {
      handler: 'src/handlers/domains/integrations.handler',
      description: 'Integrations domain API',
      needsVpc: true,
      events: [
        protectedRoute(stage, 'GET', '/integrations'),
        protectedRoute(stage, 'POST', '/integrations'),
        protectedRoute(stage, 'GET', '/integrations/dashboard/summary'),
        protectedRoute(stage, 'GET', '/integrations/zabbix/summary'),
        protectedRoute(stage, 'GET', '/integrations/zabbix/detailed'),
        protectedRoute(stage, 'GET', '/integrations/wazuh/summary'),
        protectedRoute(stage, 'GET', '/integrations/nessus/summary'),
        protectedRoute(stage, 'GET', '/integrations/uptime_kuma/summary'),
        protectedRoute(stage, 'GET', '/integrations/{integrationId}'),
        protectedRoute(stage, 'PUT', '/integrations/{integrationId}'),
        protectedRoute(stage, 'DELETE', '/integrations/{integrationId}'),
        protectedRoute(stage, 'GET', '/integrations/{integrationId}/credentials'),
      ],
    }),
    securityOpsApi: lambdaConfig(stage, {
      handler: 'src/handlers/domains/security_ops.handler',
      description: 'Security operations domain API',
      needsVpc: true,
      events: [
        protectedRoute(stage, 'GET', '/alerts/active'),
        protectedRoute(stage, 'POST', '/alerts/{alertId}/resolve'),
        protectedRoute(stage, 'GET', '/analytics/incidents'),
        protectedRoute(stage, 'GET', '/analytics/response-time'),
        protectedRoute(stage, 'GET', '/analytics/vulnerability-distribution'),
        protectedRoute(stage, 'GET', '/analytics/summary'),
        protectedRoute(stage, 'GET', '/systems/status'),
        protectedRoute(stage, 'GET', '/systems'),
        protectedRoute(stage, 'GET', '/systems/{systemId}'),
        protectedRoute(stage, 'GET', '/vulnerabilities'),
        protectedRoute(stage, 'GET', '/vulnerabilities/{vulnId}'),
        protectedRoute(stage, 'POST', '/vulnerabilities/{vulnId}/patch'),
      ],
    }),
  }),
});
