const { buildService, lambdaConfig, protectedRoute, publicRoute, stageRef } = require('./serverless/services/lib/common');

module.exports = buildService({
  service: 'xoc-api-ops',
  attachToSharedHttpApi: true,
  iam: { database: true, snapshots: true, vpc: true, agentEncryption: true },
  pythonRequirements: {
    fileName: 'requirements.crypto.txt',
    dockerizePip: true,
    dockerImage: 'public.ecr.aws/sam/build-python3.11:latest',
  },
  functions: (stage) => ({
    scansApi: lambdaConfig(stage, {
      handler: 'src/handlers/domains/scans.handler',
      description: 'Scans domain API',
      needsVpc: true,
      include: [
        'src/handlers/domains/scans.py',
        'src/handlers/routes/scans.py',
        'src/shared/**',
        'src/persistence/**',
        'requirements.crypto.txt',
      ],
      events: [
        publicRoute('POST', '/scans/ingest'),
        publicRoute('POST', '/scans/upload-url'),
        protectedRoute(stage, 'GET', '/scans'),
        protectedRoute(stage, 'GET', '/scans/latest'),
        protectedRoute(stage, 'GET', '/scans/summary'),
        protectedRoute(stage, 'GET', '/scans/{scanSummaryId}'),
        protectedRoute(stage, 'GET', '/scans/{scanSummaryId}/findings'),
        protectedRoute(stage, 'GET', '/findings/{findingId}'),
        protectedRoute(stage, 'GET', '/scans/{scannerType}/analytics'),
        protectedRoute(stage, 'GET', '/scans/snapshots'),
        protectedRoute(stage, 'GET', '/scans/snapshots/{artifactId}'),
        protectedRoute(stage, 'GET', '/scans/snapshots/{artifactId}/payload'),
        protectedRoute(stage, 'GET', '/scans/snapshots/{artifactId}/download-url'),
        protectedRoute(stage, 'GET', '/scans/agent/snapshots'),
        protectedRoute(stage, 'GET', '/scans/agent/snapshots/{artifactId}'),
        protectedRoute(stage, 'GET', '/scans/agent/snapshots/{artifactId}/payload'),
        protectedRoute(stage, 'GET', '/scans/agent/snapshots/{artifactId}/download-url'),
        protectedRoute(stage, 'GET', '/scans/agent/summaries'),
        protectedRoute(stage, 'GET', '/scans/agent/summaries/{scanSummaryId}'),
        protectedRoute(stage, 'GET', '/scans/agent/summaries/{scanSummaryId}/findings'),
        protectedRoute(stage, 'GET', '/scans/agent/findings'),
      ],
    }),
    snapshotProcessor: lambdaConfig(stage, {
      handler: 'src/handlers/processors/snapshot_processor.handler',
      description: 'Processes large snapshot uploads from S3',
      needsVpc: true,
      timeout: 120,
      memorySize: 1024,
      include: [
        'src/handlers/processors/snapshot_processor.py',
        'src/shared/**',
        'src/persistence/**',
        'requirements.txt',
      ],
      events: [
        {
          s3: {
            bucket: stageRef(stage, 'snapshotsBucketName'),
            event: 's3:ObjectCreated:*',
            rules: [{ prefix: 'pending/' }],
            existing: true,
          },
        },
      ],
    }),
    integrationsApi: lambdaConfig(stage, {
      handler: 'src/handlers/domains/integrations.handler',
      description: 'Integrations domain API',
      needsVpc: true,
      include: [
        'src/handlers/domains/integrations.py',
        'src/handlers/routes/integrations.py',
        'src/shared/**',
        'src/persistence/**',
        'src/integrations/**',
        'requirements.txt',
      ],
      events: [
        protectedRoute(stage, 'GET', '/integrations'),
        protectedRoute(stage, 'POST', '/integrations'),
        protectedRoute(stage, 'GET', '/integrations/dashboard/summary'),
        protectedRoute(stage, 'GET', '/integrations/zabbix/summary'),
        protectedRoute(stage, 'GET', '/integrations/zabbix/detailed'),
        protectedRoute(stage, 'GET', '/integrations/wazuh/summary'),
        protectedRoute(stage, 'GET', '/integrations/nessus/summary'),
        protectedRoute(stage, 'GET', '/integrations/uptime_kuma/summary'),
        protectedRoute(stage, 'GET', '/integrations/{integrationId}'),
        protectedRoute(stage, 'PUT', '/integrations/{integrationId}'),
        protectedRoute(stage, 'DELETE', '/integrations/{integrationId}'),
        protectedRoute(stage, 'GET', '/integrations/{integrationId}/credentials'),
      ],
    }),
    dashboardApi: lambdaConfig(stage, {
      handler: 'src/handlers/domains/dashboard.handler',
      description: 'Dashboard domain API',
      needsVpc: true,
      include: [
        'src/handlers/domains/dashboard.py',
        'src/handlers/routes/dashboard.py',
        'src/shared/**',
        'src/persistence/**',
        'src/integrations/**',
        'requirements.txt',
      ],
      events: [
        protectedRoute(stage, 'GET', '/dashboard/home'),
        protectedRoute(stage, 'GET', '/dashboard/providers/{provider}'),
      ],
    }),
    securityOpsApi: lambdaConfig(stage, {
      handler: 'src/handlers/domains/security_ops.handler',
      description: 'Security operations domain API',
      needsVpc: true,
      include: [
        'src/handlers/domains/security_ops.py',
        'src/handlers/routes/alerts.py',
        'src/handlers/routes/analytics.py',
        'src/handlers/routes/systems.py',
        'src/handlers/routes/vulnerabilities.py',
        'src/shared/**',
        'src/persistence/**',
        'requirements.txt',
      ],
      events: [
        protectedRoute(stage, 'GET', '/alerts/active'),
        protectedRoute(stage, 'POST', '/alerts/{alertId}/resolve'),
        protectedRoute(stage, 'GET', '/analytics/incidents'),
        protectedRoute(stage, 'GET', '/analytics/response-time'),
        protectedRoute(stage, 'GET', '/analytics/vulnerability-distribution'),
        protectedRoute(stage, 'GET', '/analytics/summary'),
        protectedRoute(stage, 'GET', '/systems/status'),
        protectedRoute(stage, 'GET', '/systems'),
        protectedRoute(stage, 'GET', '/systems/{systemId}'),
        protectedRoute(stage, 'GET', '/vulnerabilities'),
        protectedRoute(stage, 'GET', '/vulnerabilities/{vulnId}'),
        protectedRoute(stage, 'POST', '/vulnerabilities/{vulnId}/patch'),
      ],
    }),
  }),
});
