const { buildService, lambdaConfig, protectedRoute } = require('./serverless/services/lib/common');

module.exports = buildService({
  service: 'xoc-api-admin',
  attachToSharedHttpApi: true,
  iam: { database: true, vpc: true, agentEncryption: true, dynamo: true },
  pythonRequirements: {
    dockerizePip: true,
  },
  functions: (stage) => ({
    adminApi: lambdaConfig(stage, {
      handler: 'src/handlers/domains/admin.handler',
      description: 'Admin & Superadmin domain API',
      needsVpc: true,
      include: [
        'src/handlers/domains/admin.py',
        'src/handlers/routes/admin.py',
        'src/handlers/routes/superadmin.py',
        'src/handlers/routes/xoc_ops.py',
        'src/xoc_ops/**',
        'src/shared/**',
        'src/persistence/**',
        'requirements.txt',
      ],
      events: [
        protectedRoute(stage, 'POST', '/admin/agent-instances'),
        protectedRoute(stage, 'GET', '/admin/agent-instances'),
        protectedRoute(stage, 'GET', '/admin/agent-instances/{instanceId}'),
        protectedRoute(stage, 'PATCH', '/admin/agent-instances/{instanceId}'),
        protectedRoute(stage, 'PATCH', '/admin/agent-instances/{instanceId}/status'),
        protectedRoute(stage, 'DELETE', '/admin/agent-instances/{instanceId}'),
        protectedRoute(stage, 'POST', '/admin/agent-instances/{instanceId}/rotate-key'),
        protectedRoute(stage, 'GET', '/admin/agent-instances/{instanceId}/access-key'),
        protectedRoute(stage, 'GET', '/admin/activation-keys'),
        protectedRoute(stage, 'GET', '/admin/activation-keys/{keyId}/reveal'),
        protectedRoute(stage, 'GET', '/superadmin/tenants'),
        protectedRoute(stage, 'POST', '/superadmin/tenants'),
        protectedRoute(stage, 'GET', '/superadmin/tenants/{tenantId}'),
        protectedRoute(stage, 'PATCH', '/superadmin/tenants/{tenantId}'),
        protectedRoute(stage, 'POST', '/superadmin/tenants/{tenantId}/impersonation-token'),
        protectedRoute(stage, 'GET', '/superadmin/tenants/{tenantId}/integrations'),
        protectedRoute(stage, 'GET', '/superadmin/tenants/{tenantId}/capabilities'),
        protectedRoute(stage, 'GET', '/superadmin/tenants/{tenantId}/capability-templates'),
        protectedRoute(stage, 'POST', '/superadmin/users'),
        protectedRoute(stage, 'GET', '/superadmin/users'),
        protectedRoute(stage, 'GET', '/superadmin/users/{userId}'),
        protectedRoute(stage, 'PATCH', '/superadmin/users/{userId}'),
        protectedRoute(stage, 'POST', '/superadmin/users/{userId}/password-reset'),
        protectedRoute(stage, 'GET', '/superadmin/integrations'),
        protectedRoute(stage, 'GET', '/superadmin/integrations/{integrationId}'),
        protectedRoute(stage, 'PATCH', '/superadmin/integrations/{integrationId}'),
        protectedRoute(stage, 'GET', '/superadmin/integrations/{integrationId}/credentials'),
        protectedRoute(stage, 'POST', '/superadmin/integrations/{integrationId}/credentials'),
        protectedRoute(stage, 'GET', '/superadmin/agent-instances'),
        protectedRoute(stage, 'GET', '/superadmin/agent-instances/{instanceId}'),
        protectedRoute(stage, 'PATCH', '/superadmin/agent-instances/{instanceId}'),
        protectedRoute(stage, 'GET', '/superadmin/agent-instances/{instanceId}/access-key'),
        protectedRoute(stage, 'POST', '/superadmin/agent-instances/{instanceId}/rotate-key'),
        protectedRoute(stage, 'POST', '/superadmin/activation-keys'),
        protectedRoute(stage, 'GET', '/superadmin/activation-keys'),
        protectedRoute(stage, 'GET', '/superadmin/activation-keys/{keyId}/reveal'),
        protectedRoute(stage, 'PATCH', '/superadmin/activation-keys/{keyId}'),
        protectedRoute(stage, 'GET', '/superadmin/agent-keys'),
        protectedRoute(stage, 'GET', '/superadmin/agent-keys/{keyId}'),
        protectedRoute(stage, 'POST', '/superadmin/agent-keys/{keyId}/regenerate'),
        protectedRoute(stage, 'GET', '/superadmin/tickets'),
        protectedRoute(stage, 'GET', '/superadmin/tickets/{ticketId}'),
        protectedRoute(stage, 'PATCH', '/superadmin/tickets/{ticketId}'),
        protectedRoute(stage, 'GET', '/superadmin/chat/sessions'),
        protectedRoute(stage, 'GET', '/superadmin/chat/sessions/{sessionId}'),
        protectedRoute(stage, 'DELETE', '/superadmin/chat/sessions/{sessionId}'),
        protectedRoute(stage, 'GET', '/superadmin/chat/history'),
        protectedRoute(stage, 'GET', '/superadmin/audit-logs'),
        protectedRoute(stage, 'GET', '/superadmin/capability-templates'),
        protectedRoute(stage, 'GET', '/superadmin/capability-templates/{templateId}'),
        protectedRoute(stage, 'POST', '/superadmin/capability-templates'),
        protectedRoute(stage, 'PATCH', '/superadmin/capability-templates/{templateId}'),
        protectedRoute(stage, 'DELETE', '/superadmin/capability-templates/{templateId}'),
        protectedRoute(stage, 'GET', '/superadmin/capability-templates/{templateId}/tenants'),
        protectedRoute(stage, 'PUT', '/superadmin/capability-templates/{templateId}/tenants'),
        protectedRoute(stage, 'GET', '/xoc-ops/clients'),
        protectedRoute(stage, 'GET', '/xoc-ops/kpis'),
        protectedRoute(stage, 'GET', '/xoc-ops/clients/{tenantId}'),
      ],
    }),
  }),
});
