const { buildService, lambdaConfig, protectedRoute, commonEnvironment } = require('./serverless/services/lib/common');
const adminResources = require('./serverless/services/admin-resources');

module.exports = buildService({
  service: 'xoc-api-admin',
  attachToSharedHttpApi: true,
  iam: { database: true, vpc: true, jwt: true, agentEncryption: true, dynamo: true, reports: true, snapshots: true },
  environment: (stage) => ({
    ...commonEnvironment(stage),
    TENANT_DELETION_QUEUE_URL: `https://sqs.${'${aws:region}'}.amazonaws.com/${'${aws:accountId}'}/xoc-api-admin-${stage}-tenant-deletion`,
    DEMO_TENANT_NAME: 'XOC Demo',
    DEMO_REFRESH_WINDOW_HOURS: '6',
  }),
  additionalIamStatements: (stage) => ([
    {
      Effect: 'Allow',
      Action: ['sqs:SendMessage'],
      Resource: [`arn:aws:sqs:${'${aws:region}'}:${'${aws:accountId}'}:xoc-api-admin-${stage}-tenant-deletion`],
    },
  ]),
  pythonRequirements: {
    fileName: 'requirements.crypto.txt',
    dockerizePip: true,
    dockerImage: 'public.ecr.aws/sam/build-python3.11:latest',
  },
  functions: (stage) => ({
    adminApi: lambdaConfig(stage, {
      handler: 'src/handlers/domains/admin.handler',
      description: 'Admin & Superadmin domain API',
      needsVpc: true,
      include: [
        'src/handlers/domains/admin.py',
        'src/handlers/routes/admin.py',
        'src/handlers/routes/superadmin.py',
        'src/handlers/routes/xoc_ops.py',
        'src/xoc_ops/**',
        'src/reports/**',
        'src/shared/**',
        'src/persistence/**',
        'requirements.crypto.txt',
      ],
      events: [
        protectedRoute(stage, 'POST', '/admin/agent-instances'),
        protectedRoute(stage, 'GET', '/admin/agent-instances'),
        protectedRoute(stage, 'GET', '/admin/agent-instances/{instanceId}'),
        protectedRoute(stage, 'PATCH', '/admin/agent-instances/{instanceId}'),
        protectedRoute(stage, 'PATCH', '/admin/agent-instances/{instanceId}/status'),
        protectedRoute(stage, 'DELETE', '/admin/agent-instances/{instanceId}'),
        protectedRoute(stage, 'POST', '/admin/agent-instances/{instanceId}/rotate-key'),
        protectedRoute(stage, 'GET', '/admin/agent-instances/{instanceId}/access-key'),
        protectedRoute(stage, 'GET', '/admin/activation-keys'),
        protectedRoute(stage, 'GET', '/admin/activation-keys/{keyId}/reveal'),
        protectedRoute(stage, 'GET', '/superadmin/tenants'),
        protectedRoute(stage, 'POST', '/superadmin/tenants'),
        protectedRoute(stage, 'GET', '/superadmin/tenants/{tenantId}'),
        protectedRoute(stage, 'PATCH', '/superadmin/tenants/{tenantId}'),
        protectedRoute(stage, 'DELETE', '/superadmin/tenants/{tenantId}'),
        protectedRoute(stage, 'POST', '/superadmin/tenants/{tenantId}/impersonation-token'),
        protectedRoute(stage, 'GET', '/superadmin/tenants/{tenantId}/integrations'),
        protectedRoute(stage, 'GET', '/superadmin/tenants/{tenantId}/capabilities'),
        protectedRoute(stage, 'GET', '/superadmin/tenants/{tenantId}/capability-templates'),
        protectedRoute(stage, 'POST', '/superadmin/users'),
        protectedRoute(stage, 'GET', '/superadmin/users'),
        protectedRoute(stage, 'GET', '/superadmin/users/{userId}'),
        protectedRoute(stage, 'PATCH', '/superadmin/users/{userId}'),
        protectedRoute(stage, 'POST', '/superadmin/users/{userId}/password-reset'),
        protectedRoute(stage, 'GET', '/superadmin/integrations'),
        protectedRoute(stage, 'GET', '/superadmin/integrations/{integrationId}'),
        protectedRoute(stage, 'PATCH', '/superadmin/integrations/{integrationId}'),
        protectedRoute(stage, 'GET', '/superadmin/integrations/{integrationId}/credentials'),
        protectedRoute(stage, 'POST', '/superadmin/integrations/{integrationId}/credentials'),
        protectedRoute(stage, 'GET', '/superadmin/agent-instances'),
        protectedRoute(stage, 'GET', '/superadmin/agent-instances/{instanceId}'),
        protectedRoute(stage, 'PATCH', '/superadmin/agent-instances/{instanceId}'),
        protectedRoute(stage, 'GET', '/superadmin/agent-instances/{instanceId}/access-key'),
        protectedRoute(stage, 'POST', '/superadmin/agent-instances/{instanceId}/rotate-key'),
        protectedRoute(stage, 'POST', '/superadmin/activation-keys'),
        protectedRoute(stage, 'GET', '/superadmin/activation-keys'),
        protectedRoute(stage, 'GET', '/superadmin/activation-keys/{keyId}/reveal'),
        protectedRoute(stage, 'PATCH', '/superadmin/activation-keys/{keyId}'),
        protectedRoute(stage, 'GET', '/superadmin/agent-keys'),
        protectedRoute(stage, 'GET', '/superadmin/agent-keys/{keyId}'),
        protectedRoute(stage, 'POST', '/superadmin/agent-keys/{keyId}/regenerate'),
        protectedRoute(stage, 'GET', '/superadmin/tickets'),
        protectedRoute(stage, 'GET', '/superadmin/tickets/{ticketId}'),
        protectedRoute(stage, 'PATCH', '/superadmin/tickets/{ticketId}'),
        protectedRoute(stage, 'GET', '/superadmin/chat/sessions'),
        protectedRoute(stage, 'GET', '/superadmin/chat/sessions/{sessionId}'),
        protectedRoute(stage, 'DELETE', '/superadmin/chat/sessions/{sessionId}'),
        protectedRoute(stage, 'GET', '/superadmin/chat/history'),
        protectedRoute(stage, 'GET', '/superadmin/audit-logs'),
        protectedRoute(stage, 'GET', '/superadmin/capability-templates'),
        protectedRoute(stage, 'GET', '/superadmin/capability-templates/{templateId}'),
        protectedRoute(stage, 'POST', '/superadmin/capability-templates'),
        protectedRoute(stage, 'PATCH', '/superadmin/capability-templates/{templateId}'),
        protectedRoute(stage, 'DELETE', '/superadmin/capability-templates/{templateId}'),
        protectedRoute(stage, 'GET', '/superadmin/capability-templates/{templateId}/tenants'),
        protectedRoute(stage, 'PUT', '/superadmin/capability-templates/{templateId}/tenants'),
        protectedRoute(stage, 'GET', '/xoc-ops/clients'),
        protectedRoute(stage, 'GET', '/xoc-ops/kpis'),
        protectedRoute(stage, 'GET', '/xoc-ops/clients/{tenantId}'),
      ],
    }),
    tenantDeletionWorker: lambdaConfig(stage, {
      handler: 'src/handlers/workers/tenant_delete.handler',
      description: 'Deletes tenant data across SQL, DynamoDB, and S3',
      timeout: 300,
      memorySize: 1024,
      needsVpc: true,
      include: [
        'src/handlers/workers/tenant_delete.py',
        'src/shared/**',
        'src/persistence/**',
        'src/reports/**',
        'requirements.crypto.txt',
      ],
      events: [
        {
          sqs: {
            arn: { 'Fn::GetAtt': ['TenantDeletionQueue', 'Arn'] },
            batchSize: 1,
          },
        },
      ],
    }),
    demoTenantRefreshWorker: lambdaConfig(stage, {
      handler: 'src/handlers/workers/demo_tenant_refresh.handler',
      description: 'Refreshes the XOC Demo tenant with synthetic dashboard and operational data',
      timeout: 300,
      memorySize: 1024,
      needsVpc: true,
      include: [
        'src/handlers/workers/demo_tenant_refresh.py',
        'src/shared/**',
        'src/persistence/**',
        'src/reports/**',
        'scripts/**',
        'requirements.crypto.txt',
      ],
      events: [
        {
          schedule: {
            rate: 'cron(0 */6 * * ? *)',
            enabled: stage === 'prod',
          },
        },
      ],
    }),
  }),
  resources: (stage) => adminResources(stage),
});
