region: us-east-1
logLevel: DEBUG
logRetentionInDays: 14
corsAllowedOrigins:
  - http://localhost:3000
  - http://localhost:5173
  - http://localhost:5000
corsAllowedOriginsCsv: http://localhost:3000,http://localhost:5173,http://localhost:5000
jwtSecretKey: xoc-demo-dev-jwt-secret-change-me
databaseSecretArn: arn:aws:secretsmanager:${aws:region}:${aws:accountId}:secret:xoc/api/dev/database
snapshotsBucketName: xoc-dev-snapshots-placeholder
snapshotsBucketArn: arn:aws:s3:::xoc-dev-snapshots-placeholder
apiVpc: ~
