region: us-east-1
logLevel: DEBUG
logRetentionInDays: 14
corsAllowedOrigins:
  - http://localhost:3000
  - http://localhost:5173
  - http://localhost:5000
corsAllowedOriginsCsv: http://localhost:3000,http://localhost:5173,http://localhost:5000
jwtSecretKey: ""
jwtSecretKeySsmPath: ""
jwtSecretArn: ${cf:xoc-api-shared-dev.JwtSecretArn}
agentKeyEncryptionKeyArn: ${cf:xoc-api-shared-dev.AgentKeyEncryptionKeySecretArn}
agentsFunctionBaseUrl: ""
agentsFunctionRouteSophia: /api/agents/SophiaDurableAgent/run
agentsFunctionRouteSophiaHistory: /api/agents/SophiaDurableAgent/history
agentsFunctionRouteSophiaDelete: /api/agents/SophiaDurableAgent/threads
agentsFunctionRouteVictor: /api/agents/VictorDurableAgent/run
databaseSecretArn: ${cf:xoc-infra-data-dev.DatabaseSecretArn}
snapshotsBucketName: ${cf:xoc-infra-storage-dev.SnapshotsBucketName}
snapshotsBucketArn: ${cf:xoc-infra-storage-dev.SnapshotsBucketArn}
xocDocumentsBucketName: xoc-dev-documents-811776156524
xocDocumentsBucketArn: arn:aws:s3:::xoc-dev-documents-811776156524
txdxDocumentsBucketName: txdx-dev-documents-811776156524
txdxDocumentsBucketArn: arn:aws:s3:::txdx-dev-documents-811776156524
txdxDocumentTypesCsv: minority_report
minorityFoundrySecretArn: ""
ticketsPointInTimeRecoveryEnabled: false
publicRegistrationEnabled: "true"
apiVpc:
  securityGroupIds:
    - ${cf:xoc-infra-network-dev.LambdaSecurityGroupId}
  subnetIds:
    - ${cf:xoc-infra-network-dev.LambdaPrivateSubnetAId}
