region: us-east-1
logLevel: INFO
logRetentionInDays: 90
corsAllowedOrigins:
  - https://xoc-frontend.web.app
  - http://xoc-frontend.web.app
  - https://www.xoc-frontend.web.app
  - http://www.xoc-frontend.web.app
  - https://xoc-frontend.firebaseapp.com
  - https://main.d111fod5hov6vt.amplifyapp.com
  - http://main.d111fod5hov6vt.amplifyapp.com
  - https://www.main.d111fod5hov6vt.amplifyapp.com
  - http://www.main.d111fod5hov6vt.amplifyapp.com
  - http://xoc-frontend.firebaseapp.com
  - https://www.xoc-frontend.firebaseapp.com
  - http://www.xoc-frontend.firebaseapp.com
  - http://localhost:3000
  - https://localhost:3000
  - http://localhost:5173
  - https://localhost:5173
  - http://127.0.0.1:3000
  - https://127.0.0.1:3000
  - http://127.0.0.1:5173
  - https://127.0.0.1:5173
corsAllowedOriginsCsv: https://xoc-frontend.web.app,http://xoc-frontend.web.app,https://www.xoc-frontend.web.app,http://www.xoc-frontend.web.app,https://xoc-frontend.firebaseapp.com,https://main.d111fod5hov6vt.amplifyapp.com,http://main.d111fod5hov6vt.amplifyapp.com,https://www.main.d111fod5hov6vt.amplifyapp.com,http://www.main.d111fod5hov6vt.amplifyapp.com,http://xoc-frontend.firebaseapp.com,https://www.xoc-frontend.firebaseapp.com,http://www.xoc-frontend.firebaseapp.com,http://localhost:3000,https://localhost:3000,http://localhost:5173,https://localhost:5173,http://127.0.0.1:3000,https://127.0.0.1:3000,http://127.0.0.1:5173,https://127.0.0.1:5173
jwtSecretKey: ""
jwtSecretKeySsmPath: /xoc/api/prod/jwt-secret
agentsFunctionBaseUrl: https://prod-a-xoc-cons-g9hvargsfqeafeap.centralus-01.azurewebsites.net
agentsFunctionRouteSophia: /api/agents/SophiaDurableAgent/run
agentsFunctionRouteSophiaHistory: /api/agents/SophiaDurableAgent/history
agentsFunctionRouteSophiaDelete: /api/agents/SophiaDurableAgent/threads
agentsFunctionRouteVictor: /api/agents/VictorDurableAgent/run
databaseSecretArn: ${cf:xoc-infra-data-prod.DatabaseSecretArn}
snapshotsBucketName: ${cf:xoc-infra-storage-prod.SnapshotsBucketName}
snapshotsBucketArn: ${cf:xoc-infra-storage-prod.SnapshotsBucketArn}
ticketsPointInTimeRecoveryEnabled: true
apiVpc:
  securityGroupIds:
    - ${cf:xoc-infra-network-prod.LambdaSecurityGroupId}
  subnetIds:
    - ${cf:xoc-infra-network-prod.LambdaPrivateSubnetAId}
    - ${cf:xoc-infra-network-prod.LambdaPrivateSubnetBId}
