region: us-east-1
logLevel: INFO
logRetentionInDays: 90
corsAllowedOrigins:
  - "*"
corsAllowedOriginsCsv: "*"
jwtSecretKey: xoc-demo-prod-jwt-secret-change-me
databaseSecretArn: ${cf:xoc-infra-data-prod.DatabaseSecretArn}
snapshotsBucketName: ${cf:xoc-infra-storage-prod.SnapshotsBucketName}
snapshotsBucketArn: ${cf:xoc-infra-storage-prod.SnapshotsBucketArn}
apiVpc:
  securityGroupIds:
    - ${cf:xoc-infra-network-prod.LambdaSecurityGroupId}
  subnetIds:
    - ${cf:xoc-infra-network-prod.LambdaPrivateSubnetAId}
    - ${cf:xoc-infra-network-prod.LambdaPrivateSubnetBId}
