region: us-east-1
logLevel: INFO
logRetentionInDays: 30
corsAllowedOrigins:
  - https://staging.example.com
corsAllowedOriginsCsv: https://staging.example.com
jwtSecretKey: ""
jwtSecretKeySsmPath: ""
jwtSecretArn: ${cf:xoc-api-shared-staging.JwtSecretArn}
agentKeyEncryptionKeyArn: ${cf:xoc-api-shared-staging.AgentKeyEncryptionKeySecretArn}
agentsFunctionBaseUrl: ""
agentsFunctionRouteSophia: /api/agents/SophiaDurableAgent/run
agentsFunctionRouteSophiaHistory: /api/agents/SophiaDurableAgent/history
agentsFunctionRouteSophiaDelete: /api/agents/SophiaDurableAgent/threads
agentsFunctionRouteVictor: /api/agents/VictorDurableAgent/run
databaseSecretArn: ${cf:xoc-infra-data-staging.DatabaseSecretArn}
snapshotsBucketName: ${cf:xoc-infra-storage-staging.SnapshotsBucketName}
snapshotsBucketArn: ${cf:xoc-infra-storage-staging.SnapshotsBucketArn}
minorityFoundrySecretArn: ""
ticketsPointInTimeRecoveryEnabled: false
publicRegistrationEnabled: "false"
apiVpc:
  securityGroupIds:
    - ${cf:xoc-infra-network-staging.LambdaSecurityGroupId}
  subnetIds:
    - ${cf:xoc-infra-network-staging.LambdaPrivateSubnetAId}
casesTableName: xoc-api-automation-staging-cases
